version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: mtg-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtg_vectors
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: mtg-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    #only if you have nvidia gpu
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]

volumes:
  pgvector_data:
  ollama_data:
